[[redirects]]
from = "/store.json"
to = "/api/json"
status = 200

# Plausible
[[redirects]]
from = "/js/script.js"
to = "https://plausible.io/js/plausible.js"
status = 200

[[redirects]]
from = "/api/event"
to = "https://plausible.io/api/event"
status = 200
